/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.forms.Reception;

import BL.PatientView;
import BL.PersonView;
import BL.ReceptionistView;
import DAL.model.Contact;
import DAL.model.NextOfKin;
import DAL.model.Outpatient;
import DAL.model.Person;
import Gui.forms.PatientAppointment;
import Main.Utilities.Utils;
import static Main.Utilities.Utils.resetForm;
import java.awt.Font;
import java.sql.Date;
import java.util.Enumeration;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import javax.swing.AbstractButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Drazen Dragovic
 */
public class PatientMiniForm extends javax.swing.JPanel {

    private static final ReceptionistView RECEPT_VIEW = new ReceptionistView();
    private static final PatientView PATIENT_VIEW = new PatientView();
    private static final PersonView PERSON_VIEW = new PersonView();

    DefaultTableModel dtm = new DefaultTableModel();

    private int personId;
    private int patientID;

    /**
     * Creates new form DocPatientDetails
     */
    public PatientMiniForm() {
        initComponents();
        reset();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        jpDocPatDet = new javax.swing.JPanel();
        jpPatDetails = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPatDetUpd = new javax.swing.JButton();
        jpDetails = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jtfPatName = new javax.swing.JTextField();
        jtfPatSurname = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jtfPatMiddle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jtfWorkTel = new javax.swing.JTextField();
        jtfHomeTel = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jtfNokName = new javax.swing.JTextField();
        jtfNokMiddle = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jtfNokSur = new javax.swing.JTextField();
        jtfNokRelation = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaComplaint = new javax.swing.JTextArea();
        jLabel65 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dpPatDateBirth = new com.github.lgooddatepicker.components.DatePicker();
        btnAddPat = new javax.swing.JButton();
        jpPatAppo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblNewPatList = new javax.swing.JTable();
        btnAppDeta = new javax.swing.JButton();
        btnNewApp = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1080, 620));
        setMinimumSize(new java.awt.Dimension(1080, 620));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1080, 620));

        jpDocPatDet.setMaximumSize(new java.awt.Dimension(1080, 600));
        jpDocPatDet.setMinimumSize(new java.awt.Dimension(1080, 600));
        jpDocPatDet.setOpaque(false);
        jpDocPatDet.setLayout(new java.awt.BorderLayout(10, 0));

        jpPatDetails.setMaximumSize(new java.awt.Dimension(630, 600));
        jpPatDetails.setMinimumSize(new java.awt.Dimension(630, 600));
        jpPatDetails.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 20), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 51, 102));
        jPanel2.setOpaque(false);

        btnPatDetUpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/update icon.png"))); // NOI18N
        btnPatDetUpd.setLabel("Update");
        btnPatDetUpd.setPreferredSize(new java.awt.Dimension(100, 40));
        btnPatDetUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatDetUpdActionPerformed(evt);
            }
        });

        jpDetails.setOpaque(false);

        jLabel70.setText("First name :");

        jtfPatName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfPatName.setToolTipText("");

        jtfPatSurname.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfPatSurname.setToolTipText("");

        jLabel90.setText("Surname :");

        jLabel71.setText("Middle name :");

        jtfPatMiddle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel4.setText("Date of Birth :");

        jLabel11.setText("Gender:");

        bgGender.add(rbMale);
        rbMale.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rbMale.setForeground(new java.awt.Color(0, 51, 102));
        rbMale.setText("M");

        bgGender.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(0, 51, 102));
        rbFemale.setText("F");

        jLabel63.setText("Tel. Home:");

        jLabel64.setText("Tel. Work:");

        jtfWorkTel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfHomeTel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel73.setText("Middle name :");

        jLabel74.setText("First name :");

        jtfNokName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfNokName.setToolTipText("");

        jtfNokMiddle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel77.setText("Relation:");

        jLabel91.setText("Surname :");

        jtfNokSur.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfNokSur.setToolTipText("");

        jtfNokRelation.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel92.setText("Next of Kin");
        jLabel92.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jLabel94.setText("Patient");
        jLabel94.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jtaComplaint.setColumns(20);
        jtaComplaint.setRows(5);
        jtaComplaint.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(jtaComplaint);

        jLabel65.setText("Complaint:");

        javax.swing.GroupLayout jpDetailsLayout = new javax.swing.GroupLayout(jpDetails);
        jpDetails.setLayout(jpDetailsLayout);
        jpDetailsLayout.setHorizontalGroup(
            jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 374, Short.MAX_VALUE))
                    .addGroup(jpDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDetailsLayout.createSequentialGroup()
                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel73)
                                    .addComponent(jLabel74))
                                .addGap(9, 9, 9)
                                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNokName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNokMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel91)
                                    .addComponent(jLabel77))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNokRelation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNokSur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDetailsLayout.createSequentialGroup()
                                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel71)
                                        .addComponent(jLabel70)
                                        .addComponent(jLabel63)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel65))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDetailsLayout.createSequentialGroup()
                                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                                .addComponent(jtfHomeTel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel64))
                                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtfPatName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtfPatMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel90)
                                                    .addComponent(jLabel11))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfPatSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfWorkTel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpDetailsLayout.createSequentialGroup()
                                        .addComponent(dpPatDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addComponent(jScrollPane5))))
                        .addGap(25, 25, 25))))
        );
        jpDetailsLayout.setVerticalGroup(
            jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel94)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel90)
                        .addGap(44, 44, 44))
                    .addGroup(jpDetailsLayout.createSequentialGroup()
                        .addComponent(jtfPatSurname)
                        .addGap(37, 37, 37))
                    .addGroup(jpDetailsLayout.createSequentialGroup()
                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addGap(14, 14, 14))
                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                .addComponent(jtfPatName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPatMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71))))
                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(rbFemale)
                        .addComponent(rbMale))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDetailsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dpPatDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHomeTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(jtfWorkTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel92)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpDetailsLayout.createSequentialGroup()
                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel91)
                                .addGap(14, 14, 14))
                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                .addComponent(jtfNokSur)
                                .addGap(7, 7, 7)))
                        .addComponent(jtfNokRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDetailsLayout.createSequentialGroup()
                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel74)
                                .addGap(14, 14, 14))
                            .addGroup(jpDetailsLayout.createSequentialGroup()
                                .addComponent(jtfNokName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNokMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel73)
                            .addComponent(jLabel77))))
                .addGap(33, 33, 33))
        );

        btnAddPat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/add.png"))); // NOI18N
        btnAddPat.setText("Add");
        btnAddPat.setPreferredSize(new java.awt.Dimension(100, 40));
        btnAddPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnAddPat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPatDetUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPatDetUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jpPatDetailsLayout = new javax.swing.GroupLayout(jpPatDetails);
        jpPatDetails.setLayout(jpPatDetailsLayout);
        jpPatDetailsLayout.setHorizontalGroup(
            jpPatDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPatDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jpPatDetailsLayout.setVerticalGroup(
            jpPatDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDocPatDet.add(jpPatDetails, java.awt.BorderLayout.LINE_START);

        jpPatAppo.setMaximumSize(new java.awt.Dimension(450, 600));
        jpPatAppo.setMinimumSize(new java.awt.Dimension(450, 600));
        jpPatAppo.setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Patients List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel3.setOpaque(false);

        jtblNewPatList.setAutoCreateRowSorter(true);
        jtblNewPatList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblNewPatList.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtblNewPatList.setForeground(new java.awt.Color(0, 51, 102));
        jtblNewPatList.setOpaque(false);
        jtblNewPatList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblNewPatListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblNewPatList);
        jtblNewPatList.getAccessibleContext().setAccessibleName("");

        btnAppDeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/attach_icon.png"))); // NOI18N
        btnAppDeta.setLabel("Details");
        btnAppDeta.setPreferredSize(new java.awt.Dimension(100, 40));
        btnAppDeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppDetaActionPerformed(evt);
            }
        });

        btnNewApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/add.png"))); // NOI18N
        btnNewApp.setText("New");
        btnNewApp.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNewApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAppDeta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewApp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppDeta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jpPatAppoLayout = new javax.swing.GroupLayout(jpPatAppo);
        jpPatAppo.setLayout(jpPatAppoLayout);
        jpPatAppoLayout.setHorizontalGroup(
            jpPatAppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatAppoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jpPatAppoLayout.setVerticalGroup(
            jpPatAppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatAppoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDocPatDet.add(jpPatAppo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpDocPatDet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpDocPatDet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jpDocPatDet.getAccessibleContext().setAccessibleName("jpDocPatDet");

        getAccessibleContext().setAccessibleName("pnDocPatDet");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppDetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppDetaActionPerformed
        JPanel main = (JPanel) this.getParent();
        JPanel dpa = Utils.getPanelByName(main, "PatientAppointment");
        this.setVisible(false);
        dpa.setVisible(true);
        dpa.setFocusable(true);
    }//GEN-LAST:event_btnAppDetaActionPerformed

    private void btnAddPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatActionPerformed
        insertPatient();
        insertNok();
    }//GEN-LAST:event_btnAddPatActionPerformed

    private void btnNewAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAppActionPerformed
        addNewAppointment();
    }//GEN-LAST:event_btnNewAppActionPerformed

    private void btnPatDetUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatDetUpdActionPerformed
        updatePatient();
    }//GEN-LAST:event_btnPatDetUpdActionPerformed

    private void jtblNewPatListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblNewPatListMouseClicked
        int row = jtblNewPatList.getSelectedRow();
        patientID = (Integer) jtblNewPatList.getModel().getValueAt(row, 0);
        showPatientData(patientID);
        btnPatDetUpd.setVisible(true);
        btnAddPat.setVisible(false);
    }//GEN-LAST:event_jtblNewPatListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JButton btnAddPat;
    private javax.swing.JButton btnAppDeta;
    private javax.swing.JButton btnNewApp;
    private javax.swing.JButton btnPatDetUpd;
    private com.github.lgooddatepicker.components.DatePicker dpPatDateBirth;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpDetails;
    private javax.swing.JPanel jpDocPatDet;
    private javax.swing.JPanel jpPatAppo;
    private javax.swing.JPanel jpPatDetails;
    private javax.swing.JTextArea jtaComplaint;
    private javax.swing.JTable jtblNewPatList;
    private javax.swing.JTextField jtfHomeTel;
    private javax.swing.JTextField jtfNokMiddle;
    private javax.swing.JTextField jtfNokName;
    private javax.swing.JTextField jtfNokRelation;
    private javax.swing.JTextField jtfNokSur;
    private javax.swing.JTextField jtfPatMiddle;
    private javax.swing.JTextField jtfPatName;
    private javax.swing.JTextField jtfPatSurname;
    private javax.swing.JTextField jtfWorkTel;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    // End of variables declaration//GEN-END:variables

    public void reset() {
        DefaultTableModel model = (DefaultTableModel) jtblNewPatList.getModel();
        model.setRowCount(0);
        resetForm(jpDetails);
        btnAppDeta.setVisible(false);
        btnPatDetUpd.setVisible(false);
    }

    private void init() {
        loadPatients();
    }

    private void loadPatients() {
        dtm.setColumnIdentifiers(Outpatient.newPatientColumns());
        dtm.setRowCount(0);

        List<Outpatient> patients = PATIENT_VIEW.getPatients();

        Predicate<Outpatient> byType = patient -> patient.getOpTypeID() < 1;
        List<Outpatient> result = patients.stream().filter(byType).collect(Collectors.<Outpatient>toList());

        for (int i = 0; i < result.size(); i++) {

            Object[] row = new Object[Outpatient.newPatientColumns().length];
            row[0] = result.get(i).getiDOutpat();
            row[1] = result.get(i).getFirstName();
            row[2] = result.get(i).getSurname();
            row[3] = result.get(i).getBreafComplaint();

            dtm.addRow(row);
        }

        jtblNewPatList.setModel(dtm);
        jtblNewPatList.getTableHeader().setFont(new Font("Calibri", Font.BOLD, 12));
        jtblNewPatList.setRowHeight(20);

        dtm.addTableModelListener((TableModelEvent tme) -> {
            DefaultTableModel tm = (DefaultTableModel) tme.getSource();
        });
    }

    private void insertPatient() {
        Person p = new Person();
        Contact contact = new Contact();
        Outpatient op = new Outpatient();

        try {
            p.setFirstName(jtfPatName.getText());
            p.setMiddleName(jtfPatMiddle.getText());
            p.setSurname(jtfPatSurname.getText());
            for (Enumeration<AbstractButton> buttons = bgGender.getElements(); buttons.hasMoreElements();) {
                AbstractButton b = buttons.nextElement();

                if (b.isSelected() && b.getText() == "M") {
                    p.setSex(true);
                } else {
                    p.setSex(false);
                }
            }

            p.setDateOFBirth(Date.valueOf(dpPatDateBirth.getDate()));

            personId = RECEPT_VIEW.insertPerson(p);

            contact.setHomeTel(jtfHomeTel.getText());
            contact.setWorkTel(jtfWorkTel.getText());
            contact.setPersonID(personId);

            RECEPT_VIEW.insertContact(contact);

            op.setBreafComplaint(jtaComplaint.getText().toString());
            op.setPersonID(personId);

            patientID = RECEPT_VIEW.insertOutpatient(op);
            
        } catch (Exception e) {
            JOptionPane optionPane = new JOptionPane("Patient not inserted", JOptionPane.WARNING_MESSAGE);
            JDialog dialog = optionPane.createDialog("Error!");
            dialog.setAlwaysOnTop(true); // to show top of all other application
            dialog.setVisible(true); // to visible the dialog
        }
    }

    private void insertNok() {
        Person p = new Person();
        NextOfKin nok = new NextOfKin();
        Contact contact = new Contact();

        try {
            p.setFirstName(jtfNokName.getText());
            p.setMiddleName(jtfNokMiddle.getText());
            p.setSurname(jtfNokSur.getText());

            personId = RECEPT_VIEW.insertPerson(p);

            contact.setPersonID(personId);
            RECEPT_VIEW.insertContact(contact);

            nok.setRelationship(jtfNokRelation.getText());
            nok.setPersonID(personId);
            nok.setOutPatId(patientID);

            RECEPT_VIEW.insertNextOfKin(nok);
            
        } catch (Exception e) {
            JOptionPane optionPane = new JOptionPane("Patient not inserted", JOptionPane.WARNING_MESSAGE);
            JDialog dialog = optionPane.createDialog("Error!");
            dialog.setAlwaysOnTop(true); // to show top of all other application
            dialog.setVisible(true); // to visible the dialog[
        }

        JOptionPane optionPane = new JOptionPane("Patient inserted", JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog = optionPane.createDialog("Success!");
        dialog.setAlwaysOnTop(true); // to show top of all other application
        dialog.setVisible(true); // to visible the dialog

        reset();
        init();
    }

    private void showPatientData(int patientID) {
        Outpatient op = PATIENT_VIEW.getPatientById(patientID);
        Contact contact = PERSON_VIEW.getPersonContact(op.getPersonID());
        NextOfKin nok = PATIENT_VIEW.getNextOfKinById(patientID);

        jtfPatName.setText(op.getFirstName());
        jtfPatMiddle.setText(op.getMiddleName());
        jtfPatSurname.setText(op.getSurname());
        dpPatDateBirth.setDate(op.getDateOFBirth().toLocalDate());
        Boolean gender = op.getSex();
        if (gender.equals(true)) {
            rbMale.setSelected(true);
            rbFemale.setSelected(false);
        } else {
            rbMale.setSelected(false);
            rbFemale.setSelected(true);
        }
        jtaComplaint.setText(op.getBreafComplaint());
        jtfHomeTel.setText(contact.getHomeTel());
        jtfWorkTel.setText(contact.getWorkTel());
        jtfNokName.setText(nok.getFirstName());
        jtfNokMiddle.setText(nok.getMiddleName());
        jtfNokSur.setText(nok.getSurname());
        jtfNokRelation.setText(nok.getRelationship());

    }

    private void updatePatient() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void addNewAppointment() {
        Outpatient op = PATIENT_VIEW.getPatientById(patientID);

        JPanel main = (JPanel) this.getParent();
        PatientAppointment pta = (PatientAppointment) Utils.getPanelByName(main, "PatientAppointment");
        this.setVisible(false);
        pta.setVisible(true);
        pta.NewPanel(op.toString());
    }
}
