/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.forms;

import BL.PatientView;
import DAL.model.AppointmentItem;
import DAL.model.AppointmentItemType;
import DAL.model.AppointmentStatus;
import Main.Utilities.Utils;
import static Main.Utilities.Utils.resetForm;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JRootPane;

/**
 *
 * @author Drazen Dragovic
 */
public class AppointmentItemDetails extends javax.swing.JPanel {

    private static final PatientView PATIENT_VIEW = new PatientView();
    
    /**
     * Creates new form AppointmentItemDetails
     */
    public AppointmentItemDetails() {
        initComponents();
    }

    public AppointmentItemDetails(int id) {
        initComponents();
        getAppItemDet(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAppTask = new javax.swing.JPanel();
        btnAppItemUpd = new javax.swing.JButton();
        btnNewAppItem = new javax.swing.JButton();
        btnAppoint = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtfAppItemDesc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbAppItemStatus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtaResult = new javax.swing.JTextArea();
        dpAppItemDate = new com.github.lgooddatepicker.components.DatePicker();
        jtfAppItemMedPer = new javax.swing.JTextField();
        jcbAppItemType = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(617, 600));
        setMinimumSize(new java.awt.Dimension(617, 600));
        setOpaque(false);

        jpAppTask.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appointment Task", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 20), new java.awt.Color(0, 51, 102))); // NOI18N
        jpAppTask.setForeground(new java.awt.Color(0, 51, 102));
        jpAppTask.setMaximumSize(new java.awt.Dimension(617, 600));
        jpAppTask.setMinimumSize(new java.awt.Dimension(617, 600));
        jpAppTask.setOpaque(false);

        btnAppItemUpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/update icon.png"))); // NOI18N
        btnAppItemUpd.setLabel("Update");
        btnAppItemUpd.setPreferredSize(new java.awt.Dimension(100, 40));

        btnNewAppItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/add.png"))); // NOI18N
        btnNewAppItem.setText("New");
        btnNewAppItem.setPreferredSize(new java.awt.Dimension(100, 40));

        btnAppoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/user_ico.png"))); // NOI18N
        btnAppoint.setText("Appointment");
        btnAppoint.setPreferredSize(new java.awt.Dimension(100, 40));
        btnAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointActionPerformed(evt);
            }
        });

        jLabel11.setText("Description:");
        jLabel11.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jtfAppItemDesc.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfAppItemDesc.setToolTipText("");

        jLabel12.setText("Date:");
        jLabel12.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jLabel13.setText("Medic person:");
        jLabel13.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jcbAppItemStatus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel14.setText("Type:");
        jLabel14.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jLabel15.setText("Status:");
        jLabel15.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jLabel16.setText("Result:");
        jLabel16.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jtaResult.setColumns(20);
        jtaResult.setLineWrap(true);
        jtaResult.setRows(5);
        jtaResult.setWrapStyleWord(true);
        jtaResult.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtaResult.setMaximumSize(new java.awt.Dimension(200, 100));
        jtaResult.setMinimumSize(new java.awt.Dimension(200, 100));
        jScrollPane8.setViewportView(jtaResult);

        dpAppItemDate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfAppItemMedPer.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jcbAppItemType.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpAppTaskLayout = new javax.swing.GroupLayout(jpAppTask);
        jpAppTask.setLayout(jpAppTaskLayout);
        jpAppTaskLayout.setHorizontalGroup(
            jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAppTaskLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAppTaskLayout.createSequentialGroup()
                        .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfAppItemDesc)
                                .addGroup(jpAppTaskLayout.createSequentialGroup()
                                    .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfAppItemMedPer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                    .addGap(43, 43, 43)
                                    .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jcbAppItemType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAppTaskLayout.createSequentialGroup()
                                .addComponent(dpAppItemDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jpAppTaskLayout.createSequentialGroup()
                                .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAppItemUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel15)
                                        .addComponent(jcbAppItemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAppTaskLayout.createSequentialGroup()
                        .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAppoint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27))
                    .addGroup(jpAppTaskLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNewAppItem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
        );
        jpAppTaskLayout.setVerticalGroup(
            jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAppItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpAppItemDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAppTaskLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbAppItemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAppItemMedPer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAppItemType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13)
                    .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAppTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppItemUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewAppItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jpAppTask, javax.swing.GroupLayout.PREFERRED_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAppTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointActionPerformed
        JPanel main = (JPanel) this.getParent();
        JPanel apd = Utils.getPanelByName(main, "AppointmentDetails");
        apd.setVisible(true);
        apd.setFocusable(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAppointActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppItemUpd;
    private javax.swing.JButton btnAppoint;
    private javax.swing.JButton btnNewAppItem;
    private com.github.lgooddatepicker.components.DatePicker dpAppItemDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JComboBox<String> jcbAppItemStatus;
    private javax.swing.JComboBox<String> jcbAppItemType;
    private javax.swing.JPanel jpAppTask;
    private javax.swing.JTextArea jtaResult;
    private javax.swing.JTextField jtfAppItemDesc;
    private javax.swing.JTextField jtfAppItemMedPer;
    // End of variables declaration//GEN-END:variables

    private void getAppItemDet(int id) {
        Reset();
        
        AppointmentItem apd = PATIENT_VIEW.getAppointmentItemById(id);
        
        List<AppointmentStatus> appStat = PATIENT_VIEW.getAppointmentStatus();
        appStat.forEach(a -> jcbAppItemStatus.addItem(a.getAppStat()));
        
        List<AppointmentItemType> appItType = PATIENT_VIEW.getAppointmentItemType();
        appItType.forEach(a -> jcbAppItemType.addItem(a.getAppIteName()));
        
        jtfAppItemDesc.setText(apd.getAppIteDesc());
        dpAppItemDate.setDate(apd.getItemDate().toLocalDate());
        jcbAppItemStatus.setSelectedIndex(apd.getAppItemStatusID() - 1);
        jcbAppItemType.setSelectedIndex(apd.getAppItTypeID() - 1);
        jtaResult.setText(apd.getResult());
        
        
    }

    private void Reset() {
        resetForm(jpAppTask);
    }
}
