/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.forms;

import BL.DoctorView;
import BL.PatientView;
import DAL.model.Appointment;
import DAL.model.AppointmentStatus;
import DAL.model.Doctor;
import DAL.model.Outpatient;
import Main.Utilities.Utils;
import static Main.Utilities.Utils.resetForm;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Drazen Dragovic
 */
public class AppointmentDetails extends javax.swing.JPanel {

    private static final PatientView PATIENT_VIEW = new PatientView();
    private static final DoctorView DOCTOR_VIEW = new DoctorView();

    private int patId;

    /**
     * Creates new form AppointmentDetails
     */
    public AppointmentDetails() {
        initComponents();
        Utils.resetForm(jpPatApp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPatApp = new javax.swing.JPanel();
        btnPatDetUpd = new javax.swing.JButton();
        btnNewApp2 = new javax.swing.JButton();
        btnPatDet = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfAppTitle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dpAppNewDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel7 = new javax.swing.JLabel();
        jcbAppStat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaAppDiagnose = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaAppNote = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaAppSymp = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbMedicin = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        dpAppDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel10 = new javax.swing.JLabel();
        btnAppDeta3 = new javax.swing.JButton();
        jtfPatName = new javax.swing.JTextField();
        jtfDocName = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(617, 600));
        setMinimumSize(new java.awt.Dimension(617, 600));
        setPreferredSize(new java.awt.Dimension(617, 600));
        setOpaque(false);

        jpPatApp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Appointment", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 20), new java.awt.Color(0, 51, 102))); // NOI18N
        jpPatApp.setForeground(new java.awt.Color(0, 51, 102));
        jpPatApp.setMaximumSize(new java.awt.Dimension(617, 600));
        jpPatApp.setMinimumSize(new java.awt.Dimension(617, 600));
        jpPatApp.setOpaque(false);

        btnPatDetUpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/update icon.png"))); // NOI18N
        btnPatDetUpd.setLabel("Update");
        btnPatDetUpd.setPreferredSize(new java.awt.Dimension(100, 40));

        btnNewApp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/add.png"))); // NOI18N
        btnNewApp2.setText("New");
        btnNewApp2.setPreferredSize(new java.awt.Dimension(100, 40));

        btnPatDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/user_ico.png"))); // NOI18N
        btnPatDet.setText("Patient Details");
        btnPatDet.setPreferredSize(new java.awt.Dimension(100, 40));
        btnPatDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatDetActionPerformed(evt);
            }
        });

        jLabel5.setText("Name:");
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jtfAppTitle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfAppTitle.setToolTipText("");

        jLabel6.setText("Date:");
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        dpAppNewDate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel7.setText("Doctor:");
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jcbAppStat.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel1.setText("Patient:");
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jLabel2.setText("Status:");
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jLabel3.setText("Symptoms:");
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jtaAppDiagnose.setColumns(20);
        jtaAppDiagnose.setRows(5);
        jtaAppDiagnose.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(jtaAppDiagnose);

        jLabel4.setText("Diagnose:");
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jtaAppNote.setColumns(20);
        jtaAppNote.setRows(5);
        jtaAppNote.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtaAppNote.setPreferredSize(new java.awt.Dimension(200, 100));
        jScrollPane4.setViewportView(jtaAppNote);

        jtaAppSymp.setColumns(20);
        jtaAppSymp.setRows(5);
        jtaAppSymp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jScrollPane5.setViewportView(jtaAppSymp);

        jLabel8.setText("Notes:");
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jScrollPane2.setOpaque(false);

        jtbMedicin.setAutoCreateRowSorter(true);
        jtbMedicin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbMedicin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtbMedicin.setForeground(new java.awt.Color(0, 51, 102));
        jtbMedicin.setOpaque(false);
        jScrollPane2.setViewportView(jtbMedicin);

        jLabel9.setText("Prescribed medicine:");
        jLabel9.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        dpAppDate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel10.setText("New App:");
        jLabel10.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        btnAppDeta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/attach_icon.png"))); // NOI18N
        btnAppDeta3.setText("Print Bill");
        btnAppDeta3.setPreferredSize(new java.awt.Dimension(100, 40));

        jtfPatName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfDocName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpPatAppLayout = new javax.swing.GroupLayout(jpPatApp);
        jpPatApp.setLayout(jpPatAppLayout);
        jpPatAppLayout.setHorizontalGroup(
            jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPatAppLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPatAppLayout.createSequentialGroup()
                        .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfAppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPatAppLayout.createSequentialGroup()
                                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfDocName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfPatName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jcbAppStat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpAppDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPatAppLayout.createSequentialGroup()
                        .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4)
                            .addGroup(jpPatAppLayout.createSequentialGroup()
                                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpPatAppLayout.createSequentialGroup()
                                .addComponent(btnPatDet, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAppDeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPatAppLayout.createSequentialGroup()
                                .addComponent(btnNewApp2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPatDetUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dpAppNewDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jpPatAppLayout.setVerticalGroup(
            jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatAppLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpAppDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPatAppLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbAppStat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPatName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDocName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7)
                    .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPatAppLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dpAppNewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPatDet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPatAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAppDeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNewApp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPatDetUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpPatApp, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPatApp, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatDetActionPerformed
        JPanel main = (JPanel) this.getParent();
        JPanel parentmain = (JPanel) main.getParent();
        JPanel parent = (JPanel) parentmain.getParent();
        JPanel parent2 = (JPanel) parent.getParent();

        PatientDetails dpd = (PatientDetails) Utils.getPanelByName(parent2, "PatientDetails");
        parent.setVisible(false);
        dpd.setVisible(true);
        dpd.loadPatientById(patId);
        dpd.setFocusable(true);
    }//GEN-LAST:event_btnPatDetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppDeta3;
    private javax.swing.JButton btnNewApp2;
    private javax.swing.JButton btnPatDet;
    private javax.swing.JButton btnPatDetUpd;
    private com.github.lgooddatepicker.components.DatePicker dpAppDate;
    private com.github.lgooddatepicker.components.DatePicker dpAppNewDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> jcbAppStat;
    private javax.swing.JPanel jpPatApp;
    private javax.swing.JTextArea jtaAppDiagnose;
    private javax.swing.JTextArea jtaAppNote;
    private javax.swing.JTextArea jtaAppSymp;
    private javax.swing.JTable jtbMedicin;
    private javax.swing.JTextField jtfAppTitle;
    private javax.swing.JTextField jtfDocName;
    private javax.swing.JTextField jtfPatName;
    // End of variables declaration//GEN-END:variables

    public void loadAppById(int IdApp) {
        Appointment app = PATIENT_VIEW.getAppointmentById(IdApp);
        Doctor doctor = DOCTOR_VIEW.getDoctorById(app.getDoctorID());
        Outpatient patient = PATIENT_VIEW.getPatientById(app.getOutpatientID());

        patId = patient.getiDOutpat();

        Reset();

        List<AppointmentStatus> appStat = PATIENT_VIEW.getAppointmentStatus();
        appStat.forEach(a -> jcbAppStat.addItem(a.getAppStat()));

        jtfAppTitle.setText(app.getTitle());
        dpAppDate.setDate(app.getPreferredDate().toLocalDate());
        jtfDocName.setText(doctor.toString());
        jtfPatName.setText(patient.toString());
        jcbAppStat.setSelectedIndex(app.getStatusID() - 1);
        jtaAppSymp.setText(app.getSymptoms());
        jtaAppDiagnose.setText(app.getDiagnose());
        jtaAppNote.setText(app.getDiagnose());
    }
    
        private void Reset() {
        resetForm(jpPatApp);
    }
}
