/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.forms;

import BL.MedicPersonView;
import DAL.model.MedicalPerson;
import DAL.model.MedicalPersonType;
import Gui.forms.Admin.AdminMain;
import Gui.forms.Doctor.DoctorMain;
import Gui.forms.Reception.ReceptionMain;
import static Main.Utilities.Utils.*;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Drazen Dragovic
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form doctorMainFrame
     */
    public MainForm() {
        initComponents();
        SetFramePosition(this);
        FillMedTypes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        lblPAss = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        lblUserType = new javax.swing.JLabel();
        jcbUserType = new javax.swing.JComboBox<>();
        jbLogin = new javax.swing.JButton();
        javax.swing.JLabel lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 700));

        pnlMain.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlMain.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlMain.setPreferredSize(new java.awt.Dimension(1300, 700));
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlLogin.setLayout(null);

        lblUser.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 51, 102));
        lblUser.setText("USERNAME");
        pnlLogin.add(lblUser);
        lblUser.setBounds(230, 410, 110, 20);

        jtfUserName.setColumns(1);
        jtfUserName.setToolTipText("");
        jtfUserName.setAutoscrolls(false);
        pnlLogin.add(jtfUserName);
        jtfUserName.setBounds(230, 430, 280, 40);

        lblPAss.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblPAss.setForeground(new java.awt.Color(0, 51, 102));
        lblPAss.setText("PASSWORD");
        pnlLogin.add(lblPAss);
        lblPAss.setBounds(230, 480, 150, 20);

        jpfPassword.setMinimumSize(new java.awt.Dimension(14, 24));
        jpfPassword.setPreferredSize(new java.awt.Dimension(25, 24));
        pnlLogin.add(jpfPassword);
        jpfPassword.setBounds(230, 500, 280, 40);

        lblUserType.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(0, 51, 102));
        lblUserType.setText("USER TYPE");
        pnlLogin.add(lblUserType);
        lblUserType.setBounds(230, 550, 150, 20);

        jcbUserType.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        pnlLogin.add(jcbUserType);
        jcbUserType.setBounds(230, 570, 280, 40);

        jbLogin.setText("Login");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(jbLogin);
        jbLogin.setBounds(560, 570, 140, 40);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/LoginFrameLogo.jpg"))); // NOI18N
        pnlLogin.add(lblBackground);
        lblBackground.setBounds(0, 0, 1300, 700);

        pnlMain.add(pnlLogin, "card2");
        pnlLogin.getAccessibleContext().setAccessibleName("pnlLogin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static final MedicPersonView MEDPERSON_VIEW = new MedicPersonView();
    private MedicalPerson user;

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed

        List<MedicalPerson> medpersons = MEDPERSON_VIEW.getMedPersons();

        if (jtfUserName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter user name");
            return;
        }

        if (String.valueOf(jpfPassword.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter password");
            return;
        }

        for (MedicalPerson mp : medpersons) {
            if (jtfUserName.getText().equals(mp.getUserName()) && String.valueOf(jpfPassword.getPassword()).equals(mp.getPassword())) {
                user = mp;
            }
        }

        if (user == null) {
            JOptionPane optionPane = new JOptionPane("Wrong Username or Password", JOptionPane.WARNING_MESSAGE);
            JDialog dialog = optionPane.createDialog("Warning!");
            dialog.setAlwaysOnTop(true); // to show top of all other application
            dialog.setVisible(true); // to visible the dialog 
            ResetFields();
        } else {
            int usertype = user.getmPTypeID();

            if (jcbUserType.getSelectedIndex() + 1 == usertype) {
                switch (usertype) {
                    case 1:
                        DoctorMain dmp = new DoctorMain(user);
                        pnlMain.add(dmp);
                        dmp.setVisible(true);
                        ResetFields();
                        break;
                    case 3:
                        ReceptionMain rmp = new ReceptionMain(user);
                        pnlMain.add(rmp);
                        rmp.setVisible(true);
                        ResetFields();
                        break;
                    case 4:
                        AdminMain amp = new AdminMain(user);
                        pnlMain.add(amp);
                        amp.setVisible(true);
                        ResetFields();
                        break;
                    default:

                }
            } else {
                JOptionPane optionPane = new JOptionPane("Wrong User Type", JOptionPane.WARNING_MESSAGE);
                JDialog dialog = optionPane.createDialog("Warning!");
                dialog.setAlwaysOnTop(true); // to show top of all other application
                dialog.setVisible(true); // to visible the dialog
            }
        }


    }//GEN-LAST:event_jbLoginActionPerformed

    private void ResetFields() {
        jtfUserName.setText("");
        jpfPassword.setText("");
        jcbUserType.setSelectedIndex(0);
        pnlLogin.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbLogin;
    private javax.swing.JComboBox<String> jcbUserType;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfUserName;
    private javax.swing.JLabel lblPAss;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void FillMedTypes() {
        List<MedicalPersonType> medpertypes = MEDPERSON_VIEW.getMedPersonType();
        medpertypes.forEach(m -> jcbUserType.addItem(m.getName()));
    }
}
