/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.forms;

import BL.PatientView;
import DAL.model.AppointmentItem;
import Main.Utilities.Utils;
import static Main.Utilities.Utils.CloseOpenPanel;
import java.awt.Font;
import java.util.List;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Drazen Dragovic
 */
public class PatientAppointment extends javax.swing.JPanel {

    private AppointmentDetails apdt;
    private int id;

    /**
     * Creates new form DocPatientDetails
     */
    public PatientAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDocPatDet = new javax.swing.JPanel();
        jpPatAppDetails = new javax.swing.JPanel();
        jpPatAppo = new javax.swing.JPanel();
        jpAppItems = new javax.swing.JPanel();
        btnAppItemDet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPatAppItems = new javax.swing.JTable();
        jpPersc = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        btnNewApp3 = new javax.swing.JButton();
        btnPatDetUpd1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1080, 620));
        setMinimumSize(new java.awt.Dimension(1080, 620));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1080, 620));

        jpDocPatDet.setMaximumSize(new java.awt.Dimension(1080, 600));
        jpDocPatDet.setMinimumSize(new java.awt.Dimension(1080, 600));
        jpDocPatDet.setOpaque(false);
        jpDocPatDet.setLayout(new java.awt.BorderLayout(10, 0));

        jpPatAppDetails.setMaximumSize(new java.awt.Dimension(630, 600));
        jpPatAppDetails.setMinimumSize(new java.awt.Dimension(630, 600));
        jpPatAppDetails.setOpaque(false);
        jpPatAppDetails.setPreferredSize(new java.awt.Dimension(630, 600));
        jpPatAppDetails.setLayout(new java.awt.CardLayout());
        jpDocPatDet.add(jpPatAppDetails, java.awt.BorderLayout.LINE_START);

        jpPatAppo.setMaximumSize(new java.awt.Dimension(450, 600));
        jpPatAppo.setMinimumSize(new java.awt.Dimension(450, 600));
        jpPatAppo.setOpaque(false);

        jpAppItems.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appointment Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(0, 51, 102))); // NOI18N
        jpAppItems.setMaximumSize(new java.awt.Dimension(421, 290));
        jpAppItems.setMinimumSize(new java.awt.Dimension(421, 290));
        jpAppItems.setOpaque(false);
        jpAppItems.setPreferredSize(new java.awt.Dimension(421, 290));

        btnAppItemDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/attach_icon.png"))); // NOI18N
        btnAppItemDet.setLabel("Details");
        btnAppItemDet.setPreferredSize(new java.awt.Dimension(100, 40));
        btnAppItemDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppItemDetActionPerformed(evt);
            }
        });

        jScrollPane1.setOpaque(false);

        jtblPatAppItems.setAutoCreateRowSorter(true);
        jtblPatAppItems.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtblPatAppItems.setForeground(new java.awt.Color(0, 51, 102));
        jtblPatAppItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblPatAppItems.setOpaque(false);
        jtblPatAppItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblPatAppItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblPatAppItems);

        javax.swing.GroupLayout jpAppItemsLayout = new javax.swing.GroupLayout(jpAppItems);
        jpAppItems.setLayout(jpAppItemsLayout);
        jpAppItemsLayout.setHorizontalGroup(
            jpAppItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppItemsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnAppItemDet, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpAppItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpAppItemsLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        jpAppItemsLayout.setVerticalGroup(
            jpAppItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppItemsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAppItemDet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jpAppItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpAppItemsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        jpPersc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perscription:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(0, 51, 102))); // NOI18N
        jpPersc.setMaximumSize(new java.awt.Dimension(420, 290));
        jpPersc.setMinimumSize(new java.awt.Dimension(420, 290));
        jpPersc.setOpaque(false);
        jpPersc.setPreferredSize(new java.awt.Dimension(420, 290));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel17.setText("Medicine Category:");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel18.setText("Medicine Name:");

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel19.setText("Quantity:");

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel20.setText("Days:");

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel21.setText("Usage:");

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel22.setText("Description:");

        btnNewApp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/add.png"))); // NOI18N
        btnNewApp3.setText("New");
        btnNewApp3.setPreferredSize(new java.awt.Dimension(100, 40));

        btnPatDetUpd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/update icon.png"))); // NOI18N
        btnPatDetUpd1.setLabel("Update");
        btnPatDetUpd1.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jpPerscLayout = new javax.swing.GroupLayout(jpPersc);
        jpPersc.setLayout(jpPerscLayout);
        jpPerscLayout.setHorizontalGroup(
            jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPerscLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPerscLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpPerscLayout.createSequentialGroup()
                        .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField8)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPerscLayout.createSequentialGroup()
                                .addComponent(btnNewApp3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPatDetUpd1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPerscLayout.createSequentialGroup()
                                .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(jpPerscLayout.createSequentialGroup()
                                        .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19))
                                        .addGap(26, 26, 26)
                                        .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextField7)
                                    .addComponent(jComboBox7, 0, 174, Short.MAX_VALUE)
                                    .addComponent(jLabel21))))
                        .addGap(20, 20, 20))))
        );
        jpPerscLayout.setVerticalGroup(
            jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPerscLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jpPerscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewApp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatDetUpd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jpPatAppoLayout = new javax.swing.GroupLayout(jpPatAppo);
        jpPatAppo.setLayout(jpPatAppoLayout);
        jpPatAppoLayout.setHorizontalGroup(
            jpPatAppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatAppoLayout.createSequentialGroup()
                .addGroup(jpPatAppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpPersc, javax.swing.GroupLayout.PREFERRED_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(jpAppItems, javax.swing.GroupLayout.PREFERRED_SIZE, 410, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jpPatAppoLayout.setVerticalGroup(
            jpPatAppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatAppoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAppItems, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpPersc, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jpPersc.getAccessibleContext().setAccessibleName("Perscription");
        jpPersc.getAccessibleContext().setAccessibleDescription("");
        jpPersc.getAccessibleContext().setAccessibleParent(jpPatAppDetails);

        jpDocPatDet.add(jpPatAppo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDocPatDet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpDocPatDet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtblPatAppItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPatAppItemsMouseClicked
        int row = jtblPatAppItems.getSelectedRow();
        id = (Integer) jtblPatAppItems.getModel().getValueAt(row, 0);
        System.out.println(id);
    }//GEN-LAST:event_jtblPatAppItemsMouseClicked

    private void btnAppItemDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppItemDetActionPerformed
        AppointmentItemDetails aid = new AppointmentItemDetails(id);
        aid.setName("AppointmentItemDetails");
        jpPatAppDetails.add(aid);
        jpPatAppDetails.getComponent(0).setVisible(false);
        //jpPersc.setVisible(false);

        aid.setVisible(true);
    }//GEN-LAST:event_btnAppItemDetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppItemDet;
    private javax.swing.JButton btnNewApp3;
    private javax.swing.JButton btnPatDetUpd1;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel jpAppItems;
    private javax.swing.JPanel jpDocPatDet;
    private javax.swing.JPanel jpPatAppDetails;
    private javax.swing.JPanel jpPatAppo;
    private javax.swing.JPanel jpPersc;
    private javax.swing.JTable jtblPatAppItems;
    // End of variables declaration//GEN-END:variables

    public void InitPanels(int appId) {
        if (Utils.getPanelByName(jpPatAppDetails, "AppointmentDetails") != null) {
            apdt = (AppointmentDetails) Utils.getPanelByName(jpPatAppDetails, "AppointmentDetails");
            CloseOpenPanel(jpPatAppDetails);
            jpPersc.setVisible(true);
            apdt.loadAppById(appId);

        } else {
            AppointmentDetails apdt = new AppointmentDetails();
            apdt.setName("AppointmentDetails");
            CloseOpenPanel(jpPatAppDetails);
            jpPatAppDetails.add(apdt);
            apdt.loadAppById(appId);
        }
        GetAppointmentItems(appId);
    }

    public void NewPanel(String patient) {
        if (Utils.getPanelByName(jpPatAppDetails, "AppointmentDetails") != null) {
            apdt = (AppointmentDetails) Utils.getPanelByName(jpPatAppDetails, "AppointmentDetails");
            CloseOpenPanel(jpPatAppDetails);
            jpPersc.setVisible(true);
        }
        else {
            AppointmentDetails apdt = new AppointmentDetails();
            apdt.setName("AppointmentDetails");
            CloseOpenPanel(jpPatAppDetails);
            jpPatAppDetails.add(apdt);
        }
    }

    DefaultTableModel dtm = new DefaultTableModel();

    private static final PatientView PATIENT_VIEW = new PatientView();

    private void GetAppointmentItems(int appId) {
        dtm.setColumnIdentifiers(AppointmentItem.appointmentItemsColumns());
        dtm.setRowCount(0);

        List<AppointmentItem> appItems = PATIENT_VIEW.getAppointmentItemsById(appId);

        for (int i = 0; i < appItems.size(); i++) {

            Object[] row = new Object[AppointmentItem.appointmentItemsColumns().length];
            row[0] = appItems.get(i).getiDAppItem();
            row[1] = appItems.get(i).getItemDate().toLocalDate();
            row[2] = appItems.get(i).getAppItTypeID();
            row[3] = appItems.get(i).getAppItemStatusID();

            dtm.addRow(row);
        }

        jtblPatAppItems.setModel(dtm);
        jtblPatAppItems.getTableHeader().setFont(new Font("Calibri", Font.BOLD, 14));
        jtblPatAppItems.setRowHeight(20);

        dtm.addTableModelListener((TableModelEvent tme) -> {
            DefaultTableModel tm = (DefaultTableModel) tme.getSource();
        });
    }
}
