/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.forms;

import BL.PatientView;
import BL.PersonView;
import DAL.model.Appointment;
import DAL.model.Area;
import DAL.model.BasicComplaints;
import DAL.model.City;
import DAL.model.Contact;
import DAL.model.Country;
import DAL.model.Lifestyle;
import DAL.model.MedicalComplaints;
import DAL.model.MedicalPerson;
import DAL.model.NextOfKin;
import DAL.model.Outpatient;
import DAL.model.PersonAddress;
import Main.Utilities.Utils;
import static Main.Utilities.Utils.getCountryId;
import static Main.Utilities.Utils.resetForm;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Drazen Dragovic
 */
public class PatientDetails extends javax.swing.JPanel {

    private static final PatientView PATIENT_VIEW = new PatientView();
    private static final PersonView PERSON_VIEW = new PersonView();

    List<City> citys = PERSON_VIEW.GetCitys();
    List<Area> areas = PERSON_VIEW.GetAreas();
    List<Country> countrys = PERSON_VIEW.GetCountrys();

    private int patID;
    private int perID;
    private int appId;

    /**
     * Creates new form DocPatientDetails
     */
    public PatientDetails() {
        initComponents();
    }

    public PatientDetails(MedicalPerson mp) {
        initComponents();
        setMainPane(mp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        bgAddress = new javax.swing.ButtonGroup();
        jpPatDet = new javax.swing.JPanel();
        jpPatDetails = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtpPatDet = new javax.swing.JTabbedPane();
        jpBasDet = new javax.swing.JPanel();
        jtfPatID = new javax.swing.JTextField();
        jtfHeight = new javax.swing.JTextField();
        jtfBirth = new javax.swing.JTextField();
        jtfMidName = new javax.swing.JTextField();
        jtfMariState = new javax.swing.JTextField();
        jtfDepenNo = new javax.swing.JTextField();
        jtfOpid = new javax.swing.JTextField();
        jtfBloodTyp = new javax.swing.JTextField();
        jtfWeight = new javax.swing.JTextField();
        jtfSurname = new javax.swing.JTextField();
        jtfOccupa = new javax.swing.JTextField();
        jtfGai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jpContDet = new javax.swing.JPanel();
        jtfPreAdd = new javax.swing.JTextField();
        jtfTelHom = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jtfPerAdd = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jtfTelWor = new javax.swing.JTextField();
        jtfMail = new javax.swing.JTextField();
        jtfMob = new javax.swing.JTextField();
        jcbPreCity = new javax.swing.JComboBox<>();
        jcbPreState = new javax.swing.JComboBox<>();
        jcbPreArea = new javax.swing.JComboBox<>();
        jcbPerCity = new javax.swing.JComboBox<>();
        jcbPerState = new javax.swing.JComboBox<>();
        jcbPerArea = new javax.swing.JComboBox<>();
        jrbPresent = new javax.swing.JRadioButton();
        jrbPermanent = new javax.swing.JRadioButton();
        jpNok = new javax.swing.JPanel();
        jtfNokName = new javax.swing.JTextField();
        jtfNokMidName = new javax.swing.JTextField();
        jtfNokAddr = new javax.swing.JTextField();
        jtfNokTelHom = new javax.swing.JTextField();
        jtfNokMob = new javax.swing.JTextField();
        jtfRelat = new javax.swing.JTextField();
        jtfNokMail = new javax.swing.JTextField();
        jtfNokTelWork = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jtfNokSurname = new javax.swing.JTextField();
        jcbNokCity = new javax.swing.JComboBox<>();
        jcbNokState = new javax.swing.JComboBox<>();
        jcbNokArea = new javax.swing.JComboBox<>();
        jpBasComp = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaHistory = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaComplaint = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaTreated = new javax.swing.JTextArea();
        jpMedComp = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jtfDige = new javax.swing.JTextField();
        jtfRespi = new javax.swing.JTextField();
        jtfOrtho = new javax.swing.JTextField();
        jtfHyperte = new javax.swing.JTextField();
        jtfSurge = new javax.swing.JTextField();
        jtfCardi = new javax.swing.JTextField();
        jtfDiabet = new javax.swing.JTextField();
        jtfMusc = new javax.swing.JTextField();
        jtfNeuro = new javax.swing.JTextField();
        jtfAlergi = new javax.swing.JTextField();
        jtfReact = new javax.swing.JTextField();
        jpLife = new javax.swing.JPanel();
        jtfVege = new javax.swing.JTextField();
        jtfAvrCig = new javax.swing.JTextField();
        jtfSmoke = new javax.swing.JTextField();
        jtfAlcho = new javax.swing.JTextField();
        jtfAlchoNo = new javax.swing.JTextField();
        jtfStimu = new javax.swing.JTextField();
        jtfCoffe = new javax.swing.JTextField();
        jtfSoftDrink = new javax.swing.JTextField();
        jtfMeal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jtfEat = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnPatDetUpd = new javax.swing.JButton();
        btnDocPat = new javax.swing.JButton();
        jpPatAppo = new javax.swing.JPanel();
        jpAppList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPatApp = new javax.swing.JTable();
        btnAppDeta = new javax.swing.JButton();
        btnNewApp = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1080, 620));
        setMinimumSize(new java.awt.Dimension(1080, 620));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1080, 620));

        jpPatDet.setMaximumSize(new java.awt.Dimension(1080, 600));
        jpPatDet.setMinimumSize(new java.awt.Dimension(1080, 600));
        jpPatDet.setOpaque(false);
        jpPatDet.setLayout(new java.awt.BorderLayout(10, 0));

        jpPatDetails.setMaximumSize(new java.awt.Dimension(630, 600));
        jpPatDetails.setMinimumSize(new java.awt.Dimension(630, 600));
        jpPatDetails.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 20), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 51, 102));
        jPanel2.setOpaque(false);

        jtpPatDet.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtpPatDet.setMaximumSize(new java.awt.Dimension(570, 460));
        jtpPatDet.setMinimumSize(new java.awt.Dimension(570, 460));
        jtpPatDet.setPreferredSize(new java.awt.Dimension(570, 460));
        jtpPatDet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtpPatDetStateChanged(evt);
            }
        });

        jpBasDet.setMaximumSize(new java.awt.Dimension(419, 415));
        jpBasDet.setMinimumSize(new java.awt.Dimension(415, 415));
        jpBasDet.setName(""); // NOI18N
        jpBasDet.setOpaque(false);
        jpBasDet.setPreferredSize(new java.awt.Dimension(490, 415));

        jtfPatID.setEditable(false);
        jtfPatID.setToolTipText("");

        jLabel5.setText("Patient ID :");

        jLabel6.setText("Middle name :");

        jLabel4.setText("Date of Birth :");

        jLabel7.setText("Marital Stat. :");

        jLabel9.setText("OPID:");

        jLabel10.setText("Blood Type:");

        jLabel3.setText("Surname :");

        jLabel11.setText("Gender:");

        jLabel8.setText("Occupation:");

        jLabel12.setText("Height:");

        jLabel13.setText("Weight:");

        jLabel21.setText("Depend. No:");

        jLabel48.setText("First name :");

        jtfName.setToolTipText("");

        jLabel49.setText("GAI:");

        bgGender.add(rbMale);
        rbMale.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rbMale.setForeground(new java.awt.Color(0, 51, 102));
        rbMale.setText("M");

        bgGender.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(0, 51, 102));
        rbFemale.setText("F");

        javax.swing.GroupLayout jpBasDetLayout = new javax.swing.GroupLayout(jpBasDet);
        jpBasDet.setLayout(jpBasDetLayout);
        jpBasDetLayout.setHorizontalGroup(
            jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBasDetLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel21)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(9, 20, Short.MAX_VALUE)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfBloodTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOpid, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDepenNo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMariState, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMidName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPatID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel49)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(jLabel48))
                .addGap(4, 4, 4)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOccupa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBasDetLayout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addComponent(rbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jpBasDetLayout.setVerticalGroup(
            jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBasDetLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpBasDetLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14))
                    .addGroup(jpBasDetLayout.createSequentialGroup()
                        .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPatID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48)
                            .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMidName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(rbFemale)
                    .addComponent(rbMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfMariState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfOccupa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDepenNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel21))
                .addGap(36, 36, 36)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfOpid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBasDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBloodTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jtpPatDet.addTab("Basic Details", jpBasDet);

        jpContDet.setMaximumSize(new java.awt.Dimension(419, 415));
        jpContDet.setMinimumSize(new java.awt.Dimension(415, 415));
        jpContDet.setName(""); // NOI18N
        jpContDet.setOpaque(false);
        jpContDet.setPreferredSize(new java.awt.Dimension(490, 415));

        jtfPreAdd.setToolTipText("");

        jLabel22.setText("Address:");

        jLabel50.setText("Area:");

        jLabel55.setText("State");

        jLabel63.setText("Tel. Home:");

        jLabel64.setText("Tel. Work:");

        jLabel65.setText("Mobile:");

        jLabel66.setText("E-mail:");

        jLabel68.setText("City:");

        jLabel92.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel92.setText("Present Address");

        jLabel93.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel93.setText("Permanent Address");

        jLabel51.setText("Address:");

        jLabel52.setText("Area:");

        jtfPerAdd.setToolTipText("");

        jLabel72.setText("City:");

        jLabel56.setText("State");

        bgAddress.add(jrbPresent);

        bgAddress.add(jrbPermanent);

        javax.swing.GroupLayout jpContDetLayout = new javax.swing.GroupLayout(jpContDet);
        jpContDet.setLayout(jpContDetLayout);
        jpContDetLayout.setHorizontalGroup(
            jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContDetLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContDetLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbPreArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPreAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel68)
                            .addComponent(jLabel72)
                            .addComponent(jLabel56))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpContDetLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfMail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfTelWor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbPerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbPerState, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jcbPreCity, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbPreState, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jpContDetLayout.createSequentialGroup()
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(jLabel65))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTelHom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMob, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel66))
                        .addGap(211, 211, 211))))
            .addGroup(jpContDetLayout.createSequentialGroup()
                .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContDetLayout.createSequentialGroup()
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpContDetLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpContDetLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbPresent)
                            .addComponent(jrbPermanent)))
                    .addGroup(jpContDetLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50)
                            .addComponent(jLabel52)
                            .addGroup(jpContDetLayout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addGap(18, 18, 18)
                                .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbPerArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfPerAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpContDetLayout.setVerticalGroup(
            jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContDetLayout.createSequentialGroup()
                .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContDetLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbPresent)
                            .addComponent(jLabel92))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPreAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel68))
                        .addGap(7, 7, 7)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(jLabel55)
                            .addComponent(jcbPreArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel93)
                            .addComponent(jrbPermanent))
                        .addGap(18, 18, 18)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51))
                        .addGap(7, 7, 7)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(jLabel56)
                            .addComponent(jcbPerArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel63)
                            .addComponent(jtfTelHom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel65)
                            .addComponent(jtfMob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpContDetLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jcbPreCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbPreState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel72)
                            .addComponent(jcbPerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbPerState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfTelWor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel64))
                        .addGap(10, 10, 10)
                        .addGroup(jpContDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel66))))
                .addGap(80, 80, 80))
        );

        jtpPatDet.addTab("Contact Details", jpContDet);

        jpNok.setMaximumSize(new java.awt.Dimension(419, 415));
        jpNok.setMinimumSize(new java.awt.Dimension(415, 415));
        jpNok.setName(""); // NOI18N
        jpNok.setOpaque(false);
        jpNok.setPreferredSize(new java.awt.Dimension(490, 415));

        jtfNokName.setToolTipText("");

        jtfNokTelWork.setToolTipText("");

        jLabel70.setText("First name :");

        jLabel71.setText("Middle name :");

        jLabel76.setText("Relation:");

        jLabel81.setText("Address:");

        jLabel82.setText("Area:");

        jLabel83.setText("City:");

        jLabel84.setText("State:");

        jLabel85.setText("Tel. Home:");

        jLabel86.setText("Tel. Work:");

        jLabel87.setText("Mobile:");

        jLabel88.setText("E-mail:");

        jLabel90.setText("Surname :");

        jtfNokSurname.setToolTipText("");

        javax.swing.GroupLayout jpNokLayout = new javax.swing.GroupLayout(jpNok);
        jpNok.setLayout(jpNokLayout);
        jpNokLayout.setHorizontalGroup(
            jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNokLayout.createSequentialGroup()
                .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNokLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel87)
                            .addComponent(jLabel85)
                            .addComponent(jLabel82)
                            .addComponent(jLabel81)
                            .addComponent(jLabel71)
                            .addComponent(jLabel70))
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNokLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNokName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNokMidName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpNokLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNokAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNokTelHom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNokMob, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbNokArea, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel90)
                            .addComponent(jLabel76)
                            .addComponent(jLabel83)
                            .addComponent(jLabel84)
                            .addComponent(jLabel86)
                            .addComponent(jLabel88))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbNokState, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbNokCity, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNokLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNokSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfRelat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNokTelWork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNokMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jpNokLayout.setVerticalGroup(
            jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNokLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpNokLayout.createSequentialGroup()
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpNokLayout.createSequentialGroup()
                                .addComponent(jLabel90)
                                .addGap(14, 14, 14))
                            .addGroup(jpNokLayout.createSequentialGroup()
                                .addComponent(jtfNokSurname)
                                .addGap(7, 7, 7)))
                        .addComponent(jtfRelat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jcbNokCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbNokState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNokTelWork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jtfNokMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpNokLayout.createSequentialGroup()
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpNokLayout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addGap(14, 14, 14))
                            .addGroup(jpNokLayout.createSequentialGroup()
                                .addComponent(jtfNokName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNokMidName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71)
                            .addComponent(jLabel76))
                        .addGap(35, 35, 35)
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNokAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel81)
                            .addComponent(jLabel83))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel82)
                            .addComponent(jLabel84)
                            .addComponent(jcbNokArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNokTelHom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel85)
                            .addComponent(jLabel86))
                        .addGap(6, 6, 6)
                        .addGroup(jpNokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNokMob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel87)
                            .addComponent(jLabel88))))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jtpPatDet.addTab("Next-of-Kin", jpNok);

        jpBasComp.setMaximumSize(new java.awt.Dimension(490, 415));
        jpBasComp.setMinimumSize(new java.awt.Dimension(490, 415));
        jpBasComp.setOpaque(false);

        jLabel29.setText("Statement of Complaint::");

        jLabel30.setText("History of Previous Treatment::");

        jLabel31.setText("Physician/Hospital Treated::");

        jtaHistory.setColumns(20);
        jtaHistory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtaHistory.setRows(5);
        jtaHistory.setMaximumSize(new java.awt.Dimension(220, 80));
        jtaHistory.setMinimumSize(new java.awt.Dimension(220, 80));
        jScrollPane2.setViewportView(jtaHistory);

        jtaComplaint.setColumns(20);
        jtaComplaint.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtaComplaint.setRows(5);
        jtaComplaint.setMaximumSize(new java.awt.Dimension(220, 80));
        jtaComplaint.setMinimumSize(new java.awt.Dimension(220, 80));
        jScrollPane3.setViewportView(jtaComplaint);

        jtaTreated.setColumns(20);
        jtaTreated.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtaTreated.setRows(5);
        jScrollPane4.setViewportView(jtaTreated);

        javax.swing.GroupLayout jpBasCompLayout = new javax.swing.GroupLayout(jpBasComp);
        jpBasComp.setLayout(jpBasCompLayout);
        jpBasCompLayout.setHorizontalGroup(
            jpBasCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBasCompLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpBasCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBasCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpBasCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addGroup(jpBasCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel30)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jpBasCompLayout.setVerticalGroup(
            jpBasCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBasCompLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4)
                .addGap(21, 21, 21))
        );

        jtpPatDet.addTab("Basic Complaints", jpBasComp);

        jpMedComp.setMaximumSize(new java.awt.Dimension(490, 415));
        jpMedComp.setMinimumSize(new java.awt.Dimension(490, 415));
        jpMedComp.setOpaque(false);

        jLabel32.setText("Cardiac Condition:");

        jLabel33.setText("Respiratory Condition:");
        jLabel33.setToolTipText("");

        jLabel34.setText("Digestive Condition:");
        jLabel34.setToolTipText("");

        jLabel37.setText("Orthopedic Condition:");

        jLabel38.setText("Muscular Condition:");

        jLabel40.setText("Neurological Condition:");

        jLabel42.setText("Known Allergies:");

        jLabel44.setText("Adverse Reaction to Specific Drugs:");

        jLabel45.setText("Major Surgeries:");

        jLabel46.setText("Hypertensive:");

        jLabel47.setText("Diabetic:");

        jtfDige.setToolTipText("");

        jtfRespi.setToolTipText("");

        jtfOrtho.setToolTipText("");

        jtfHyperte.setToolTipText("");

        jtfSurge.setToolTipText("");

        jtfCardi.setToolTipText("");

        jtfDiabet.setToolTipText("");

        jtfMusc.setToolTipText("");

        jtfNeuro.setToolTipText("");

        jtfAlergi.setToolTipText("");

        jtfReact.setToolTipText("");

        javax.swing.GroupLayout jpMedCompLayout = new javax.swing.GroupLayout(jpMedComp);
        jpMedComp.setLayout(jpMedCompLayout);
        jpMedCompLayout.setHorizontalGroup(
            jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMedCompLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel40)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addGap(18, 18, 18)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfHyperte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jtfCardi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfRespi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfDige, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfOrtho, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNeuro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfSurge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfAlergi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfReact, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfMusc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfDiabet))
                .addGap(27, 27, 27))
        );
        jpMedCompLayout.setVerticalGroup(
            jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMedCompLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDiabet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHyperte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCardi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRespi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDige, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfOrtho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMusc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNeuro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAlergi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfReact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMedCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSurge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addGap(22, 22, 22))
        );

        jtpPatDet.addTab("Medical Complaints", jpMedComp);

        jpLife.setMaximumSize(new java.awt.Dimension(490, 415));
        jpLife.setMinimumSize(new java.awt.Dimension(490, 415));
        jpLife.setOpaque(false);

        jtfVege.setToolTipText("");

        jLabel23.setText("Vegetarian:");

        jLabel24.setText("Smoker:");

        jLabel25.setText("Consume Alcoholic Beverage:");
        jLabel25.setToolTipText("");

        jLabel26.setText("Use Stimulants:");

        jLabel35.setText("Consumption of Coffee-Tea/Day:");

        jLabel36.setText("Consumption of Soft Drinks/Day:");

        jLabel39.setText("Have Regular Meals:");

        jLabel41.setText("Eat Home Food/Outside Predominantly?:");

        jLabel27.setText("Average No. of Cigarettes/Day:");

        jLabel28.setText("Average No. of Drinks/Day:");
        jLabel28.setToolTipText("");

        javax.swing.GroupLayout jpLifeLayout = new javax.swing.GroupLayout(jpLife);
        jpLife.setLayout(jpLifeLayout);
        jpLifeLayout.setHorizontalGroup(
            jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
            .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpLifeLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel41)
                        .addComponent(jLabel39)
                        .addComponent(jLabel36)
                        .addComponent(jLabel35)
                        .addComponent(jLabel26)
                        .addComponent(jLabel28)
                        .addComponent(jLabel25)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel23))
                    .addGap(18, 18, 18)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfVege, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(jtfSmoke, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfMeal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfSoftDrink, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfCoffe, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfStimu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfAlchoNo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfAlcho, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfAvrCig, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfEat))
                    .addGap(29, 29, 29)))
        );
        jpLifeLayout.setVerticalGroup(
            jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpLifeLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfVege, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfSmoke, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfAvrCig, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfAlcho, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfAlchoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfStimu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfCoffe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfSoftDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpLifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfEat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41))
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        jtpPatDet.addTab("Lifestyle", jpLife);

        btnPatDetUpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/update icon.png"))); // NOI18N
        btnPatDetUpd.setLabel("Update");
        btnPatDetUpd.setPreferredSize(new java.awt.Dimension(100, 40));

        btnDocPat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/user_ico.png"))); // NOI18N
        btnDocPat.setText("Patient");
        btnDocPat.setPreferredSize(new java.awt.Dimension(100, 40));
        btnDocPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocPatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDocPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPatDetUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtpPatDet, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpPatDet, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPatDetUpd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDocPat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jpPatDetailsLayout = new javax.swing.GroupLayout(jpPatDetails);
        jpPatDetails.setLayout(jpPatDetailsLayout);
        jpPatDetailsLayout.setHorizontalGroup(
            jpPatDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPatDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jpPatDetailsLayout.setVerticalGroup(
            jpPatDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPatDet.add(jpPatDetails, java.awt.BorderLayout.LINE_START);

        jpPatAppo.setMaximumSize(new java.awt.Dimension(450, 600));
        jpPatAppo.setMinimumSize(new java.awt.Dimension(450, 600));
        jpPatAppo.setOpaque(false);

        jpAppList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appointments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(0, 51, 102))); // NOI18N
        jpAppList.setOpaque(false);

        jtblPatApp.setAutoCreateRowSorter(true);
        jtblPatApp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtblPatApp.setForeground(new java.awt.Color(0, 51, 102));
        jtblPatApp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblPatApp.setOpaque(false);
        jtblPatApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblPatAppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblPatApp);
        jtblPatApp.getAccessibleContext().setAccessibleName("");

        btnAppDeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/attach_icon.png"))); // NOI18N
        btnAppDeta.setLabel("Details");
        btnAppDeta.setPreferredSize(new java.awt.Dimension(100, 40));
        btnAppDeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppDetaActionPerformed(evt);
            }
        });

        btnNewApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/add.png"))); // NOI18N
        btnNewApp.setText("New");
        btnNewApp.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jpAppListLayout = new javax.swing.GroupLayout(jpAppList);
        jpAppList.setLayout(jpAppListLayout);
        jpAppListLayout.setHorizontalGroup(
            jpAppListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppListLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpAppListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAppListLayout.createSequentialGroup()
                        .addComponent(btnAppDeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jpAppListLayout.setVerticalGroup(
            jpAppListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpAppListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppDeta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jpPatAppoLayout = new javax.swing.GroupLayout(jpPatAppo);
        jpPatAppo.setLayout(jpPatAppoLayout);
        jpPatAppoLayout.setHorizontalGroup(
            jpPatAppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatAppoLayout.createSequentialGroup()
                .addComponent(jpAppList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jpPatAppoLayout.setVerticalGroup(
            jpPatAppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPatAppoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAppList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPatDet.add(jpPatAppo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPatDet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpPatDet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jpPatDet.getAccessibleContext().setAccessibleName("jpDocPatDet");

        getAccessibleContext().setAccessibleName("pnDocPatDet");
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocPatActionPerformed
        JPanel main = (JPanel) this.getParent();
        JPanel dp = Utils.getPanelByName(main, "DocPatient");
        this.setVisible(false);
        dp.setVisible(true);
        dp.setFocusable(true);
    }//GEN-LAST:event_btnDocPatActionPerformed

    private void btnAppDetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppDetaActionPerformed
        JPanel main = (JPanel) this.getParent();
        PatientAppointment dpa = (PatientAppointment) Utils.getPanelByName(main, "PatientAppointment");
        this.setVisible(false);
        dpa.setVisible(true);
        dpa.setFocusable(true);
        dpa.InitPanels(appId);
    }//GEN-LAST:event_btnAppDetaActionPerformed

    private void jtpPatDetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtpPatDetStateChanged
        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();
        switch (index) {
            case 1:
                loadContDetails();
                break;
            case 2:
                loadNextOfKin();
                break;
            case 3:
                loadBasicCompl();
                break;
            case 4:
                loadMedicCompl();
                break;
            case 5:
                loadLifeStyle();
                break;
        }
    }//GEN-LAST:event_jtpPatDetStateChanged

    private void jtblPatAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPatAppMouseClicked
        int row = jtblPatApp.getSelectedRow();
        appId = (Integer) jtblPatApp.getModel().getValueAt(row, 0);
        System.out.println(appId);
    }//GEN-LAST:event_jtblPatAppMouseClicked

    class handler implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == jrbPresent) {
                jtfPreAdd.setEditable(true);
                jcbPreCity.setEnabled(true);
                jcbPreArea.setEnabled(true);
                jcbPreState.setEnabled(true);
                jtfPerAdd.setEditable(false);
                jcbPerCity.setEnabled(false);
                jcbPerArea.setEnabled(false);
                jcbPerState.setEnabled(false);

            } else if (e.getSource() == jrbPermanent) {
                jtfPerAdd.setEditable(true);
                jcbPerCity.setEnabled(true);
                jcbPerArea.setEnabled(true);
                jcbPerState.setEnabled(true);
                jtfPreAdd.setEditable(false);
                jcbPreCity.setEnabled(false);
                jcbPreArea.setEnabled(false);
                jcbPreState.setEnabled(false);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAddress;
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JButton btnAppDeta;
    private javax.swing.JButton btnDocPat;
    private javax.swing.JButton btnNewApp;
    private javax.swing.JButton btnPatDetUpd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jcbNokArea;
    private javax.swing.JComboBox<String> jcbNokCity;
    private javax.swing.JComboBox<String> jcbNokState;
    private javax.swing.JComboBox<String> jcbPerArea;
    private javax.swing.JComboBox<String> jcbPerCity;
    private javax.swing.JComboBox<String> jcbPerState;
    private javax.swing.JComboBox<String> jcbPreArea;
    private javax.swing.JComboBox<String> jcbPreCity;
    private javax.swing.JComboBox<String> jcbPreState;
    private javax.swing.JPanel jpAppList;
    private javax.swing.JPanel jpBasComp;
    private javax.swing.JPanel jpBasDet;
    private javax.swing.JPanel jpContDet;
    private javax.swing.JPanel jpLife;
    private javax.swing.JPanel jpMedComp;
    private javax.swing.JPanel jpNok;
    private javax.swing.JPanel jpPatAppo;
    private javax.swing.JPanel jpPatDet;
    private javax.swing.JPanel jpPatDetails;
    private javax.swing.JRadioButton jrbPermanent;
    private javax.swing.JRadioButton jrbPresent;
    private javax.swing.JTextArea jtaComplaint;
    private javax.swing.JTextArea jtaHistory;
    private javax.swing.JTextArea jtaTreated;
    private javax.swing.JTable jtblPatApp;
    private javax.swing.JTextField jtfAlcho;
    private javax.swing.JTextField jtfAlchoNo;
    private javax.swing.JTextField jtfAlergi;
    private javax.swing.JTextField jtfAvrCig;
    private javax.swing.JTextField jtfBirth;
    private javax.swing.JTextField jtfBloodTyp;
    private javax.swing.JTextField jtfCardi;
    private javax.swing.JTextField jtfCoffe;
    private javax.swing.JTextField jtfDepenNo;
    private javax.swing.JTextField jtfDiabet;
    private javax.swing.JTextField jtfDige;
    private javax.swing.JTextField jtfEat;
    private javax.swing.JTextField jtfGai;
    private javax.swing.JTextField jtfHeight;
    private javax.swing.JTextField jtfHyperte;
    private javax.swing.JTextField jtfMail;
    private javax.swing.JTextField jtfMariState;
    private javax.swing.JTextField jtfMeal;
    private javax.swing.JTextField jtfMidName;
    private javax.swing.JTextField jtfMob;
    private javax.swing.JTextField jtfMusc;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfNeuro;
    private javax.swing.JTextField jtfNokAddr;
    private javax.swing.JTextField jtfNokMail;
    private javax.swing.JTextField jtfNokMidName;
    private javax.swing.JTextField jtfNokMob;
    private javax.swing.JTextField jtfNokName;
    private javax.swing.JTextField jtfNokSurname;
    private javax.swing.JTextField jtfNokTelHom;
    private javax.swing.JTextField jtfNokTelWork;
    private javax.swing.JTextField jtfOccupa;
    private javax.swing.JTextField jtfOpid;
    private javax.swing.JTextField jtfOrtho;
    private javax.swing.JTextField jtfPatID;
    private javax.swing.JTextField jtfPerAdd;
    private javax.swing.JTextField jtfPreAdd;
    private javax.swing.JTextField jtfReact;
    private javax.swing.JTextField jtfRelat;
    private javax.swing.JTextField jtfRespi;
    private javax.swing.JTextField jtfSmoke;
    private javax.swing.JTextField jtfSoftDrink;
    private javax.swing.JTextField jtfStimu;
    private javax.swing.JTextField jtfSurge;
    private javax.swing.JTextField jtfSurname;
    private javax.swing.JTextField jtfTelHom;
    private javax.swing.JTextField jtfTelWor;
    private javax.swing.JTextField jtfVege;
    private javax.swing.JTextField jtfWeight;
    private javax.swing.JTabbedPane jtpPatDet;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    // End of variables declaration//GEN-END:variables

    private void setMainPane(MedicalPerson mp) {
        if (mp.getmPTypeID() == 1) {
            System.out.println("Doctor");
        }
        if (mp.getmPTypeID() == 3) {
            System.out.println("Recep");
            btnDocPat.setVisible(false);

            handler h = new handler();
            jrbPresent.addActionListener(h);
            jrbPermanent.addActionListener(h);

        }
        if (mp.getmPTypeID() == 4) {
            System.out.println("Admin");
        }
    }

    public void loadPatientById(int iDPat) {

        jtpPatDet.setSelectedIndex(0);
        btnAppDeta.setVisible(true);
        Outpatient patient = PATIENT_VIEW.getPatientById(iDPat);

        resetForm(jpBasDet);

        if (patient == null) {
            return;
        } else {
            patID = patient.getiDOutpat();
            perID = patient.getPersonID();

            jtfPatID.setText(Integer.toString(patient.getiDOutpat()));
            jtfName.setText(patient.getFirstName());
            jtfMidName.setText(patient.getMiddleName());
            jtfSurname.setText(patient.getSurname());
            jtfName.setText(patient.getFirstName());
            jtfBirth.setText(patient.getDateOFBirth().toLocalDate().toString());
            Boolean gender = patient.getSex();
            if (gender.equals(true)) {
                rbMale.setSelected(true);
            } else {
                rbFemale.setSelected(true);
            }
            jtfMariState.setText(patient.getMaritalStatus());
            jtfOccupa.setText(patient.getOccupation());
            jtfDepenNo.setText(Integer.toString(patient.getNoDependents()));
            jtfGai.setText(Double.toString(patient.getGaIncome()));
            jtfOpid.setText(Integer.toString(patient.getoPNumber()));
            jtfHeight.setText(Double.toString(patient.getoPHeight()));
            jtfWeight.setText(Double.toString(patient.getOpWeight()));
            jtfBloodTyp.setText(patient.getOpBloodType());

        }
    }

    private void loadContDetails() {
        Contact patCont = PERSON_VIEW.getPersonContact(perID);
        PersonAddress patAddr = PERSON_VIEW.getPersonAddress(perID);

        if (patCont == null || patAddr == null) {
            InitPreComBox();
            InitPerComBox();
        } else {
            resetForm(jpContDet);

            if (patAddr.getAddrTypeID() == 1) {

                InitPreComBox();
                jrbPresent.setSelected(true);

                jtfPreAdd.setText(patAddr.toString());
                jcbPreCity.setSelectedIndex(patAddr.getCityID() - 1);
                jcbPreArea.setSelectedIndex(patAddr.getAreaID() - 1);
                jcbPreState.setSelectedIndex(getCountryId(patAddr.getCityID()) - 1);

                jrbPermanent.setSelected(false);
                jtfPerAdd.setEditable(false);
                jcbPerCity.setEnabled(false);
                jcbPerArea.setEnabled(false);
                jcbPerState.setEnabled(false);

            } else {

                InitPerComBox();
                jrbPermanent.setSelected(true);

                jtfPerAdd.setText(patAddr.toString());
                jcbPerCity.setSelectedIndex(patAddr.getCityID() - 1);
                jcbPerArea.setSelectedIndex(patAddr.getAreaID() - 1);
                jcbPerState.setSelectedIndex(getCountryId(patAddr.getCityID()) - 1);

                jrbPresent.setSelected(false);
                jtfPreAdd.setEditable(false);
                jcbPreCity.setEnabled(false);
                jcbPreArea.setEnabled(false);
                jcbPreState.setEnabled(false);

            }
        }
        jtfTelHom.setText(patCont.getHomeTel());
        jtfTelWor.setText(patCont.getWorkTel());
        jtfMob.setText(patCont.getMobile());
        jtfMail.setText(patCont.getEmail());
    }

    private void loadNextOfKin() {
        NextOfKin nok = PATIENT_VIEW.getNextOfKinById(patID);
        Contact nokCont = PERSON_VIEW.getPersonContact(nok.getPersonID());
        PersonAddress nokAddr = PERSON_VIEW.getPersonAddress(nok.getPersonID());

        if (nokCont == null || nokAddr == null) {
            InitNokComBox();
        } else {
            jtfNokTelHom.setText(nokCont.getHomeTel());
            jtfNokTelWork.setText(nokCont.getWorkTel());
            jtfNokMob.setText(nokCont.getMobile());
            jtfNokMail.setText(nokCont.getEmail());
            jtfNokAddr.setText(nokAddr.toString());
            jcbNokCity.setSelectedIndex(nokAddr.getCityID() - 1);
            jcbNokArea.setSelectedIndex(nokAddr.getAreaID() - 1);
            jcbNokState.setSelectedIndex(getCountryId(nokAddr.getCityID()) - 1);
        }

        jtfNokName.setText(nok.getFirstName());
        jtfNokSurname.setText(nok.getSurname());
        jtfNokMidName.setText(nok.getMiddleName());
        jtfRelat.setText(nok.getRelationship());
    }

    private void loadBasicCompl() {
        BasicComplaints pbc = PATIENT_VIEW.getBasComplById(patID);

        if (pbc == null) {
            return;
        } else {
            jtaComplaint.setText(pbc.getStateCompl());
            jtaHistory.setText(pbc.getHistPrevTreat());
            jtaTreated.setText(pbc.getHospTreat());
        }

    }

    private void loadMedicCompl() {
        MedicalComplaints pmc = PATIENT_VIEW.getMedComplById(patID);

        if (pmc == null) {
            return;
        } else {
            jtfDiabet.setText(pmc.getDiabetic());
            jtfHyperte.setText(pmc.getHypertensive());
            jtfCardi.setText(pmc.getCardiacCond());
            jtfRespi.setText(pmc.getRespCond());
            jtfDige.setText(pmc.getDigCon());
            jtfOrtho.setText(pmc.getOrthCon());
            jtfMusc.setText(pmc.getMuscCon());
            jtfNeuro.setText(pmc.getNeurCon());
            jtfAlergi.setText(pmc.getAllergies());
            jtfReact.setText(pmc.getReactSpecDrug());
            jtfSurge.setText(pmc.getSurgeries());
        }

    }

    private void loadLifeStyle() {
        Lifestyle pls = PATIENT_VIEW.getLifestlById(perID);

        if (pls == null) {
            return;
        } else {
            jtfVege.setText((pls.isVegeterian()) ? "Vegetarian" : "Non-Vegetarian");
            jtfSmoke.setText((pls.isSmoker()) ? "Yes" : "No");
            jtfAvrCig.setText(Integer.toString(pls.getAvNoCigarNo()));
            jtfAlcho.setText((pls.isConAlcBever()) ? "Yes" : "No");
            jtfAlchoNo.setText(Integer.toString(pls.getAvNoDrinksNo()));
            jtfStimu.setText(pls.getStimulants());
            jtfCoffe.setText(Integer.toString(pls.getConCoffeTea()));
            jtfSoftDrink.setText(Integer.toString(pls.getConSoftDrinks()));
            jtfMeal.setText(pls.getRegularMeals());
            jtfEat.setText(pls.getHomeFood());
        }

    }

    private void InitPreComBox() {
        citys.forEach(c -> jcbPreCity.addItem(c.getName()));
        areas.forEach(c -> jcbPreArea.addItem(c.getName()));
        countrys.forEach(a -> jcbPreState.addItem(a.getName()));
    }

    private void InitPerComBox() {
        citys.forEach(c -> jcbPerCity.addItem(c.getName()));
        areas.forEach(a -> jcbPerArea.addItem(a.getName()));
        countrys.forEach(a -> jcbPerState.addItem(a.getName()));
    }

    private void InitNokComBox() {
        citys.forEach(c -> jcbNokCity.addItem(c.getName()));
        areas.forEach(a -> jcbNokArea.addItem(a.getName()));
        countrys.forEach(a -> jcbNokState.addItem(a.getName()));
    }

    DefaultTableModel dtm = new DefaultTableModel();

    public void loadList(int idPat) {

        dtm.setRowCount(0);

        dtm.setColumnIdentifiers(Appointment.appointmentPatColumns());

        List<Appointment> appointments = PATIENT_VIEW.getAppointmentsForPatient(idPat);

        for (int i = 0; i < appointments.size(); i++) {

            Object[] row = new Object[Appointment.appointmentPatColumns().length];
            row[0] = appointments.get(i).getiDAppoint();
            row[1] = appointments.get(i).getTitle();
            row[2] = appointments.get(i).getPreferredDate().toLocalDate();
            row[3] = appointments.get(i).getDoctorID();

            dtm.addRow(row);
        }

        jtblPatApp.setModel(dtm);
        jtblPatApp.getTableHeader().setFont(new Font("Calibri", Font.BOLD, 14));
        jtblPatApp.setRowHeight(20);

        ListSelectionModel select = jtblPatApp.getSelectionModel();
        select.setSelectionInterval(0, 0);
        select.setSelectionMode(0);
        jtblPatApp.setDefaultEditor(Object.class, null);

        dtm.addTableModelListener((TableModelEvent tme) -> {
            DefaultTableModel tm = (DefaultTableModel) tme.getSource();
        });
    }

    public void reset() {
        patID = 0;
        perID = 0;
        appId = 0;
        resetForm(jpAppList);
        resetForm(jpBasDet);
        resetForm(jpBasComp);
        resetForm(jpContDet);
        resetForm(jpNok);
        resetForm(jpMedComp);
        resetForm(jpLife);
        resetForm(jpAppList);
        btnAppDeta.setVisible(false);
    }
}
