/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.forms;

import BL.PatientView;
import DAL.model.Outpatient;
import Main.Utilities.Utils;
import static Main.Utilities.Utils.resetForm;
import java.awt.Font;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Drazen Dragovic
 */
public class PatientsList extends javax.swing.JPanel {

    private TableRowSorter<DefaultTableModel> patSorter;
    private int id;

    /**
     * Creates new form DocPatientDetails
     */
    public PatientsList() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPatList = new javax.swing.JPanel();
        jpList = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPatients = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        btnPatListDeta = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1080, 620));
        setMinimumSize(new java.awt.Dimension(1080, 620));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1080, 620));

        jpPatList.setMaximumSize(new java.awt.Dimension(1080, 600));
        jpPatList.setMinimumSize(new java.awt.Dimension(1080, 600));
        jpPatList.setOpaque(false);
        jpPatList.setLayout(new java.awt.BorderLayout(10, 0));

        jpList.setMaximumSize(new java.awt.Dimension(630, 600));
        jpList.setMinimumSize(new java.awt.Dimension(630, 600));
        jpList.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patients List", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 20), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 51, 102));
        jPanel2.setOpaque(false);

        jtPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtPatients);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel4.setMaximumSize(new java.awt.Dimension(395, 65));
        jPanel4.setMinimumSize(new java.awt.Dimension(395, 65));
        jPanel4.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Patient ID:");

        jtfSearch.setMaximumSize(new java.awt.Dimension(180, 30));
        jtfSearch.setMinimumSize(new java.awt.Dimension(180, 30));
        jtfSearch.setPreferredSize(new java.awt.Dimension(180, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        btnPatListDeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/attach_icon.png"))); // NOI18N
        btnPatListDeta.setLabel("Details");
        btnPatListDeta.setPreferredSize(new java.awt.Dimension(100, 40));
        btnPatListDeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatListDetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPatListDeta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPatListDeta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jpListLayout = new javax.swing.GroupLayout(jpList);
        jpList.setLayout(jpListLayout);
        jpListLayout.setHorizontalGroup(
            jpListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpListLayout.setVerticalGroup(
            jpListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPatList.add(jpList, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPatList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpPatList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getAccessibleContext().setAccessibleName("pnDocPatList");
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatListDetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatListDetaActionPerformed
        JPanel main = (JPanel) this.getParent();
        PatientDetails dp = (PatientDetails) Utils.getPanelByName(main, "PatientDetails");
        this.setVisible(false);
        dp.setVisible(true);
        dp.loadPatientById(id);
        dp.loadList(id);
    }//GEN-LAST:event_btnPatListDetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPatListDeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpList;
    private javax.swing.JPanel jpPatList;
    private javax.swing.JTable jtPatients;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables

    private void init() {
        loadPatients();
        addDocuListener();
        addTableSelectListener();
    }

    private void addTableSelectListener() {
        jtPatients.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                int viewRow = jtPatients.getSelectedRow();
                if (viewRow < 0) {
                    return;
                } else {
                    int modelRow = jtPatients.convertRowIndexToModel(viewRow);
                    id = (Integer) jtPatients.getModel().getValueAt(modelRow, 0);
                }
            }
        }
        );
    }

    private void addDocuListener() {
        jtfSearch.getDocument().addDocumentListener(
                new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                newFilter();
            }

            public void insertUpdate(DocumentEvent e) {
                newFilter();
            }

            public void removeUpdate(DocumentEvent e) {
                newFilter();
            }

            private void newFilter() {
                RowFilter<DefaultTableModel, Object> rf = null;
                try {
                    rf = RowFilter.regexFilter(jtfSearch.getText(), 0);
                } catch (java.util.regex.PatternSyntaxException e) {
                    return;
                }
                patSorter.setRowFilter(rf);
            }
        });
    }

    DefaultTableModel dtm = new DefaultTableModel();

    private static final PatientView PATIENT_VIEW = new PatientView();

    private void loadPatients() {
        dtm.setColumnIdentifiers(Outpatient.patientColumns());

        List<Outpatient> patients = PATIENT_VIEW.getPatients();

        for (int i = 0; i < patients.size(); i++) {

            Object[] row = new Object[Outpatient.patientColumns().length];
            row[0] = patients.get(i).getiDOutpat();
            row[1] = patients.get(i).getFirstName();
            row[2] = patients.get(i).getMiddleName();
            row[3] = patients.get(i).getSurname();
            row[4] = patients.get(i).getDateOFBirth().toLocalDate();
            row[5] = patients.get(i).getOpBloodType();
            row[6] = patients.get(i).getoPNumber();

            dtm.addRow(row);
        }
        
        patSorter = new TableRowSorter<DefaultTableModel>(dtm);

        jtPatients.setModel(dtm);
        jtPatients.getTableHeader().setFont(new Font("Calibri", Font.BOLD, 14));
        jtPatients.setRowHeight(20);
        jtPatients.setRowSorter(patSorter);
        jtPatients.setDefaultEditor(Object.class, null);

        dtm.addTableModelListener((TableModelEvent tme) -> {
            DefaultTableModel tm = (DefaultTableModel) tme.getSource();
        });
    }

    public void reset() {
        resetForm(jpPatList);
        jtfSearch.setText("");
        ListSelectionModel select = jtPatients.getSelectionModel();
        select.setSelectionInterval(0, 0);
        select.setSelectionMode(0);
    }
}
