/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.forms.Doctor;

import DAL.model.MedicalPerson;
import Gui.forms.PatientsList;
import Gui.forms.PatientsAppsList;
import Gui.forms.PatientDetails;
import Gui.forms.PatientAppointment;
import Gui.forms.PerscriptList;
import Gui.forms.PrescriptDetails;
import Main.Utilities.Utils;
import static Main.Utilities.Utils.CloseOpenPanel;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Drazen Dragovic
 */
public class DoctorMain extends javax.swing.JPanel {

    /**
     * Creates new form DoctorMainPanel
     */
    public DoctorMain() {
        initComponents();
        InitDocPanels();
    }

    public DoctorMain(MedicalPerson doctor) {
        initComponents();
        InitDocPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMain = new javax.swing.JPanel();
        jpDocNav = new javax.swing.JPanel();
        jifNav = new javax.swing.JInternalFrame();
        jmbDocNav = new javax.swing.JMenuBar();
        jmDocPat = new javax.swing.JMenu();
        jmDocApp = new javax.swing.JMenu();
        jmDocPer = new javax.swing.JMenu();
        jmDocStat = new javax.swing.JMenu();
        jpDocFooter = new javax.swing.JPanel();
        javax.swing.JLabel lblInfo = new javax.swing.JLabel();
        jpDocInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JLabel1 = new javax.swing.JLabel();
        lblDocName = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        lblDocSurname = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        JLabel4 = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jpDocCont = new javax.swing.JPanel();
        jpBack = new javax.swing.JPanel();
        jlblBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1300, 700));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jpMain.setMaximumSize(new java.awt.Dimension(1300, 700));
        jpMain.setMinimumSize(new java.awt.Dimension(1300, 700));
        jpMain.setOpaque(false);
        jpMain.setPreferredSize(new java.awt.Dimension(1300, 700));
        jpMain.setLayout(new java.awt.BorderLayout(10, 10));

        jpDocNav.setBackground(new java.awt.Color(51, 153, 255));
        jpDocNav.setMaximumSize(new java.awt.Dimension(1300, 30));
        jpDocNav.setMinimumSize(new java.awt.Dimension(1300, 30));
        jpDocNav.setPreferredSize(new java.awt.Dimension(1300, 30));

        jifNav.setBackground(new java.awt.Color(51, 153, 255));
        jifNav.setBorder(null);
        jifNav.setMaximumSize(new java.awt.Dimension(1300, 30));
        jifNav.setMinimumSize(new java.awt.Dimension(1300, 30));
        jifNav.setOpaque(false);
        jifNav.setPreferredSize(new java.awt.Dimension(1300, 30));
        jifNav.setRequestFocusEnabled(false);
        jifNav.setVisible(true);

        jmbDocNav.setBorder(null);
        jmbDocNav.setMaximumSize(new java.awt.Dimension(1300, 30));
        jmbDocNav.setMinimumSize(new java.awt.Dimension(1300, 30));
        jmbDocNav.setOpaque(false);
        jmbDocNav.setPreferredSize(new java.awt.Dimension(1300, 30));

        jmDocPat.setForeground(new java.awt.Color(0, 51, 102));
        jmDocPat.setText("Patients");
        jmDocPat.setFocusable(false);
        jmDocPat.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jmDocPat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmDocPat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmDocPat.setRequestFocusEnabled(false);
        jmDocPat.setRolloverEnabled(true);
        jmDocPat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmDocPatMouseClicked(evt);
            }
        });
        jmbDocNav.add(jmDocPat);

        jmDocApp.setBorder(null);
        jmDocApp.setForeground(new java.awt.Color(0, 51, 102));
        jmDocApp.setText("Appointments");
        jmDocApp.setFocusable(false);
        jmDocApp.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jmDocApp.setRequestFocusEnabled(false);
        jmDocApp.setRolloverEnabled(true);
        jmDocApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmDocAppMouseClicked(evt);
            }
        });
        jmbDocNav.add(jmDocApp);

        jmDocPer.setBorder(null);
        jmDocPer.setForeground(new java.awt.Color(0, 51, 102));
        jmDocPer.setText("Prescriptions");
        jmDocPer.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jmDocPer.setRequestFocusEnabled(false);
        jmDocPer.setRolloverEnabled(true);
        jmDocPer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmDocPerMouseClicked(evt);
            }
        });
        jmbDocNav.add(jmDocPer);

        jmDocStat.setForeground(new java.awt.Color(0, 51, 102));
        jmDocStat.setText("Statistics");
        jmDocStat.setFocusable(false);
        jmDocStat.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jmDocStat.setRequestFocusEnabled(false);
        jmDocStat.setRolloverEnabled(true);
        jmDocStat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmDocStatMouseClicked(evt);
            }
        });
        jmbDocNav.add(jmDocStat);

        jifNav.setJMenuBar(jmbDocNav);

        javax.swing.GroupLayout jifNavLayout = new javax.swing.GroupLayout(jifNav.getContentPane());
        jifNav.getContentPane().setLayout(jifNavLayout);
        jifNavLayout.setHorizontalGroup(
            jifNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jifNavLayout.setVerticalGroup(
            jifNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpDocNavLayout = new javax.swing.GroupLayout(jpDocNav);
        jpDocNav.setLayout(jpDocNavLayout);
        jpDocNavLayout.setHorizontalGroup(
            jpDocNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jifNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpDocNavLayout.setVerticalGroup(
            jpDocNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDocNavLayout.createSequentialGroup()
                .addComponent(jifNav, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BasicInternalFrameUI bi = (BasicInternalFrameUI)jifNav.getUI();
        bi.setNorthPane(null);

        jpMain.add(jpDocNav, java.awt.BorderLayout.PAGE_START);

        jpDocFooter.setBackground(new java.awt.Color(102, 153, 0));
        jpDocFooter.setMaximumSize(new java.awt.Dimension(1300, 30));
        jpDocFooter.setMinimumSize(new java.awt.Dimension(1300, 30));
        jpDocFooter.setPreferredSize(new java.awt.Dimension(1300, 30));

        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Powered by Outpatient Manager, 2018");
        lblInfo.setFocusable(false);
        lblInfo.setMaximumSize(new java.awt.Dimension(1300, 30));
        lblInfo.setMinimumSize(new java.awt.Dimension(1300, 30));
        lblInfo.setPreferredSize(new java.awt.Dimension(1300, 30));

        javax.swing.GroupLayout jpDocFooterLayout = new javax.swing.GroupLayout(jpDocFooter);
        jpDocFooter.setLayout(jpDocFooterLayout);
        jpDocFooterLayout.setHorizontalGroup(
            jpDocFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpDocFooterLayout.setVerticalGroup(
            jpDocFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblInfo.getAccessibleContext().setAccessibleName("lblInfo");

        jpMain.add(jpDocFooter, java.awt.BorderLayout.PAGE_END);

        jpDocInfo.setBackground(new java.awt.Color(185, 233, 242));
        jpDocInfo.setMaximumSize(new java.awt.Dimension(210, 615));
        jpDocInfo.setMinimumSize(new java.awt.Dimension(210, 615));
        jpDocInfo.setPreferredSize(new java.awt.Dimension(210, 615));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(180, 570));
        jPanel1.setMinimumSize(new java.awt.Dimension(180, 570));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 570));

        JLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        JLabel1.setForeground(new java.awt.Color(0, 51, 102));
        JLabel1.setText("Name:");

        lblDocName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDocName.setToolTipText("");

        JLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        JLabel2.setForeground(new java.awt.Color(0, 51, 102));
        JLabel2.setText("Surname:");

        lblDocSurname.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDocSurname.setToolTipText("");

        JLabel3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        JLabel3.setForeground(new java.awt.Color(0, 51, 102));
        JLabel3.setText("Start Time:");

        lblStartTime.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblStartTime.setToolTipText("");

        JLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        JLabel4.setForeground(new java.awt.Color(0, 51, 102));
        JLabel4.setText("End Time:");

        lblEndTime.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEndTime.setToolTipText("");

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setPreferredSize(new java.awt.Dimension(100, 40));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDocSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDocName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDocName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDocSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jpDocInfoLayout = new javax.swing.GroupLayout(jpDocInfo);
        jpDocInfo.setLayout(jpDocInfoLayout);
        jpDocInfoLayout.setHorizontalGroup(
            jpDocInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDocInfoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jpDocInfoLayout.setVerticalGroup(
            jpDocInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDocInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpMain.add(jpDocInfo, java.awt.BorderLayout.LINE_START);

        jpDocCont.setMaximumSize(new java.awt.Dimension(1080, 595));
        jpDocCont.setMinimumSize(new java.awt.Dimension(1080, 595));
        jpDocCont.setOpaque(false);
        jpDocCont.setPreferredSize(new java.awt.Dimension(1080, 595));
        jpDocCont.setLayout(new java.awt.CardLayout());
        jpMain.add(jpDocCont, java.awt.BorderLayout.CENTER);

        jlblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/back.jpg"))); // NOI18N
        jlblBack.setFocusable(false);
        jlblBack.setMaximumSize(new java.awt.Dimension(1300, 700));
        jlblBack.setMinimumSize(new java.awt.Dimension(1300, 700));
        jlblBack.setPreferredSize(new java.awt.Dimension(1300, 700));

        javax.swing.GroupLayout jpBackLayout = new javax.swing.GroupLayout(jpBack);
        jpBack.setLayout(jpBackLayout);
        jpBackLayout.setHorizontalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpBackLayout.createSequentialGroup()
                    .addComponent(jlblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpBackLayout.setVerticalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
            .addGroup(jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpBackLayout.createSequentialGroup()
                    .addComponent(jlblBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 33, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpBack, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 33, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("pnDocPat");
    }// </editor-fold>//GEN-END:initComponents

    private void InitDocPanels() {
        PatientsList dpl = new PatientsList();
        dpl.setName("PatientsList");
        jpDocCont.add(dpl);
        dpl.setVisible(true);

        PatientDetails dpd = new PatientDetails();
        dpd.setName("PatientDetails");
        jpDocCont.add(dpd);

        PatientAppointment dpa = new PatientAppointment();
        dpa.setName("PatientAppointment");
        jpDocCont.add(dpa);

        DocPatient dp = new DocPatient();
        dp.setName("DocPatient");
        jpDocCont.add(dp);

        PatientsAppsList dpal = new PatientsAppsList();
        dpal.setName("PatientsAppsList");
        jpDocCont.add(dpal);

        DocPatientsStat dps = new DocPatientsStat();
        dps.setName("DocPatientsStat");
        jpDocCont.add(dps);

        PerscriptList psl = new PerscriptList();
        psl.setName("PerscriptList");
        jpDocCont.add(psl);

        PrescriptDetails psd = new PrescriptDetails();
        psd.setName("PrescriptDetails");
        jpDocCont.add(psd);
    }

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        JPanel main = (JPanel) jpMain.getParent();
        main.getComponent(0).setVisible(true);
        jpDocCont.removeAll();
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jmDocAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmDocAppMouseClicked
        JPanel dpal = Utils.getPanelByName(jpDocCont, "PatientsAppsList");
        CloseOpenPanel(jpDocCont);
        dpal.setVisible(true);
    }//GEN-LAST:event_jmDocAppMouseClicked

    private void jmDocPatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmDocPatMouseClicked
        JPanel dpl = Utils.getPanelByName(jpDocCont, "PatientsList");
        CloseOpenPanel(jpDocCont);
        dpl.setVisible(true);
    }//GEN-LAST:event_jmDocPatMouseClicked

    private void jmDocStatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmDocStatMouseClicked
        JPanel dps = Utils.getPanelByName(jpDocCont, "DocPatientsStat");
        CloseOpenPanel(jpDocCont);
        dps.setVisible(true);
    }//GEN-LAST:event_jmDocStatMouseClicked

    private void jmDocPerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmDocPerMouseClicked
        JPanel psl = Utils.getPanelByName(jpDocCont, "PerscriptList");
        CloseOpenPanel(jpDocCont);
        psl.setVisible(true);
    }//GEN-LAST:event_jmDocPerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JInternalFrame jifNav;
    private javax.swing.JLabel jlblBack;
    private javax.swing.JMenu jmDocApp;
    private javax.swing.JMenu jmDocPat;
    private javax.swing.JMenu jmDocPer;
    private javax.swing.JMenu jmDocStat;
    private javax.swing.JMenuBar jmbDocNav;
    private javax.swing.JPanel jpBack;
    private javax.swing.JPanel jpDocCont;
    private javax.swing.JPanel jpDocFooter;
    private javax.swing.JPanel jpDocInfo;
    private javax.swing.JPanel jpDocNav;
    private javax.swing.JPanel jpMain;
    private javax.swing.JLabel lblDocName;
    private javax.swing.JLabel lblDocSurname;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblStartTime;
    // End of variables declaration//GEN-END:variables

}
